[proxmox]
pvehost ansible_host=IP_DE_TON_PROXMOX ansible_user=B2ZO ansible_become=true ansible_become_method=sudo

[proxmox:vars]
ct_ids=152,153,154
ct_hostname_prefix=mcb2zo
ct_password=Minecraft123!
ct_cores=2
ct_memory=2048
ct_rootfs_gb=10
ct_bridge=vmbr1
ct_gateway=10.10.10.1
ct_base_ip=10.10.10.
ct_mtu=1400
ct_nameserver=1.1.1.1
ct_template=local:vztmpl/debian-12-standard_12.12-1_amd64.tar.zst
ct_storage=local

[minecraft]
mc-152 ansible_host=10.10.10.152
mc-153 ansible_host=10.10.10.153
mc-154 ansible_host=10.10.10.154

[minecraft:vars]
ansible_user=root
ansible_password=Minecraft123!
ansible_python_interpreter=/usr/bin/python3
